In [53]:
import pandas as pd
import numpy as np

In [54]:
df = pd.read_csv("../data/UHPC_Cleaned.csv")

In [55]:
df.head()

,Mix_ID,Cement Amount (kg/m³),Cement type,Cement Grade (Mpa),Silica Fume (kg/m³),Flayash Amount (kg/m³),Limestone Powder (kg/m3),Quartzpowder (kg/m3),Glass powder (kg/m3),Rice husk ash (kg/m3),...,Type of Fiber,Amount / Quantity of Fiber,Length (mm),Diameter (mm),Amount (kg/m³).1,Type of Superplasticizer,Amount (kg/m³).2,Specimen,Testing Standard,28-Day
0,S10-F10,839.0,Type I/II low-alkali portland cement,52.5,104.0,104.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,56.50,100 x 100 x 100,BS1881,135.0
1,S10-F5-N5,839.0,Type I/II low-alkali portland cement,52.5,104.0,52.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,59.33,100 x 100 x 100,BS1881,132.0
2,S10-F2.5-N7.5,839.0,Type I/II low-alkali portland cement,52.5,104.0,26.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,59.33,100 x 100 x 100,BS1881,122.5
3,S10-N10,839.0,Type I/II low-alkali portland cement,52.5,104.0,0.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,62.15,100 x 100 x 100,BS1881,116.0
4,S10-F5-M5,839.0,Type I/II low-alkali portland cement,52.5,104.0,52.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,64.98,100 x 100 x 100,BS1881,134.0

In [56]:
df.shape

(2188, 31)

In [57]:
print(df.columns.tolist())

['Mix_ID', 'Cement Amount  (kg/m³)', 'Cement type', 'Cement Grade (Mpa)', 'Silica Fume (kg/m³)', 'Flayash Amount   (kg/m³)', 'Limestone Powder  (kg/m3)', 'Quartzpowder (kg/m3)', 'Glass powder (kg/m3)', 'Rice husk ash (kg/m3)', 'Metakaolin (kg/m³)', 'GGBFS  (kg/m³)', 'Slag Amount   (kg/m³)', 'Nano-CaCO3 (kg/m3)', 'Nano-Al2O3 (kg/m3)', 'Nano-TiO2 (kg/m3)', 'Nano Silica (kg/m3)', 'Filler (kg/m³)', 'Amount  (kg/m³)', 'Sand Type', 'Max Size (mm)', 'Type of Fiber', 'Amount / Quantity of Fiber', 'Length (mm)', 'Diameter (mm)', 'Amount  (kg/m³).1', 'Type of Superplasticizer', 'Amount  (kg/m³).2', 'Specimen', 'Testing Standard', '28-Day']

In [58]:
df.columns

Index(['Mix_ID', 'Cement Amount  (kg/m³)', 'Cement type', 'Cement Grade (Mpa)',
       'Silica Fume (kg/m³)', 'Flayash Amount   (kg/m³)',
       'Limestone Powder  (kg/m3)', 'Quartzpowder (kg/m3)',
       'Glass powder (kg/m3)', 'Rice husk ash (kg/m3)', 'Metakaolin (kg/m³)',
       'GGBFS  (kg/m³)', 'Slag Amount   (kg/m³)', 'Nano-CaCO3 (kg/m3)',
       'Nano-Al2O3 (kg/m3)', 'Nano-TiO2 (kg/m3)', 'Nano Silica (kg/m3)',
       'Filler (kg/m³)', 'Amount  (kg/m³)', 'Sand Type', 'Max Size (mm)',
       'Type of Fiber', 'Amount / Quantity of Fiber', 'Length (mm)',
       'Diameter (mm)', 'Amount  (kg/m³).1', 'Type of Superplasticizer',
       'Amount  (kg/m³).2', 'Specimen', 'Testing Standard', '28-Day'],
      dtype='str')

In [59]:
df.isnull().sum()

Mix_ID                        0
Cement Amount  (kg/m³)        0
Cement type                   0
Cement Grade (Mpa)            0
Silica Fume (kg/m³)           0
Flayash Amount   (kg/m³)      0
Limestone Powder  (kg/m3)     0
Quartzpowder (kg/m3)          0
Glass powder (kg/m3)          0
Rice husk ash (kg/m3)         0
Metakaolin (kg/m³)            0
GGBFS  (kg/m³)                0
Slag Amount   (kg/m³)         0
Nano-CaCO3 (kg/m3)            0
Nano-Al2O3 (kg/m3)            0
Nano-TiO2 (kg/m3)             0
Nano Silica (kg/m3)           0
Filler (kg/m³)                0
Amount  (kg/m³)               0
Sand Type                     0
Max Size (mm)                 0
Type of Fiber                 0
Amount / Quantity of Fiber    0
Length (mm)                   0
Diameter (mm)                 0
Amount  (kg/m³).1             0
Type of Superplasticizer      0
Amount  (kg/m³).2             0
Specimen                      0
Testing Standard              0
28-Day                        0
dtype: int64

In [60]:
X = df.drop("Compressive_Strength",axis=1)
y = df["Compressive_Strength"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

KeyError: "['Compressive_Strength'] not found in axis"

In [ ]:
print(df.columns)

Index(['Mix_ID', 'Cement Amount  (kg/m³)', 'Cement type', 'Cement Grade (Mpa)',
       'Silica Fume (kg/m³)', 'Flayash Amount   (kg/m³)',
       'Limestone Powder  (kg/m3)', 'Quartzpowder (kg/m3)',
       'Glass powder (kg/m3)', 'Rice husk ash (kg/m3)', 'Metakaolin (kg/m³)',
       'GGBFS  (kg/m³)', 'Slag Amount   (kg/m³)', 'Nano-CaCO3 (kg/m3)',
       'Nano-Al2O3 (kg/m3)', 'Nano-TiO2 (kg/m3)', 'Nano Silica (kg/m3)',
       'Filler (kg/m³)', 'Amount  (kg/m³)', 'Sand Type', 'Max Size (mm)',
       'Type of Fiber', 'Amount / Quantity of Fiber', 'Length (mm)',
       'Diameter (mm)', 'Amount  (kg/m³).1', 'Type of Superplasticizer',
       'Amount  (kg/m³).2', 'Specimen', 'Testing Standard', '28-Day'],
      dtype='str')

In [ ]:
for col in df.columns:
    print(col)

Mix_ID
Cement Amount  (kg/m³)
Cement type
Cement Grade (Mpa)
Silica Fume (kg/m³)
Flayash Amount   (kg/m³)
Limestone Powder  (kg/m3)
Quartzpowder (kg/m3)
Glass powder (kg/m3)
Rice husk ash (kg/m3)
Metakaolin (kg/m³)
GGBFS  (kg/m³)
Slag Amount   (kg/m³)
Nano-CaCO3 (kg/m3)
Nano-Al2O3 (kg/m3)
Nano-TiO2 (kg/m3)
Nano Silica (kg/m3)
Filler (kg/m³)
Amount  (kg/m³)
Sand Type
Max Size (mm)
Type of Fiber
Amount / Quantity of Fiber
Length (mm)
Diameter (mm)
Amount  (kg/m³).1
Type of Superplasticizer
Amount  (kg/m³).2
Specimen
Testing Standard
28-Day

In [ ]:
df.columns.tolist()

['Mix_ID',
 'Cement Amount  (kg/m³)',
 'Cement type',
 'Cement Grade (Mpa)',
 'Silica Fume (kg/m³)',
 'Flayash Amount   (kg/m³)',
 'Limestone Powder  (kg/m3)',
 'Quartzpowder (kg/m3)',
 'Glass powder (kg/m3)',
 'Rice husk ash (kg/m3)',
 'Metakaolin (kg/m³)',
 'GGBFS  (kg/m³)',
 'Slag Amount   (kg/m³)',
 'Nano-CaCO3 (kg/m3)',
 'Nano-Al2O3 (kg/m3)',
 'Nano-TiO2 (kg/m3)',
 'Nano Silica (kg/m3)',
 'Filler (kg/m³)',
 'Amount  (kg/m³)',
 'Sand Type',
 'Max Size (mm)',
 'Type of Fiber',
 'Amount / Quantity of Fiber',
 'Length (mm)',
 'Diameter (mm)',
 'Amount  (kg/m³).1',
 'Type of Superplasticizer',
 'Amount  (kg/m³).2',
 'Specimen',
 'Testing Standard',
 '28-Day']

In [ ]:
print(df.columns.tolist())

['Mix_ID', 'Cement Amount  (kg/m³)', 'Cement type', 'Cement Grade (Mpa)', 'Silica Fume (kg/m³)', 'Flayash Amount   (kg/m³)', 'Limestone Powder  (kg/m3)', 'Quartzpowder (kg/m3)', 'Glass powder (kg/m3)', 'Rice husk ash (kg/m3)', 'Metakaolin (kg/m³)', 'GGBFS  (kg/m³)', 'Slag Amount   (kg/m³)', 'Nano-CaCO3 (kg/m3)', 'Nano-Al2O3 (kg/m3)', 'Nano-TiO2 (kg/m3)', 'Nano Silica (kg/m3)', 'Filler (kg/m³)', 'Amount  (kg/m³)', 'Sand Type', 'Max Size (mm)', 'Type of Fiber', 'Amount / Quantity of Fiber', 'Length (mm)', 'Diameter (mm)', 'Amount  (kg/m³).1', 'Type of Superplasticizer', 'Amount  (kg/m³).2', 'Specimen', 'Testing Standard', '28-Day']

In [61]:
import pandas as pd
df = pd.read_csv("../data/UHPC_Cleaned.csv")

In [62]:
df.head()

,Mix_ID,Cement Amount (kg/m³),Cement type,Cement Grade (Mpa),Silica Fume (kg/m³),Flayash Amount (kg/m³),Limestone Powder (kg/m3),Quartzpowder (kg/m3),Glass powder (kg/m3),Rice husk ash (kg/m3),...,Type of Fiber,Amount / Quantity of Fiber,Length (mm),Diameter (mm),Amount (kg/m³).1,Type of Superplasticizer,Amount (kg/m³).2,Specimen,Testing Standard,28-Day
0,S10-F10,839.0,Type I/II low-alkali portland cement,52.5,104.0,104.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,56.50,100 x 100 x 100,BS1881,135.0
1,S10-F5-N5,839.0,Type I/II low-alkali portland cement,52.5,104.0,52.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,59.33,100 x 100 x 100,BS1881,132.0
2,S10-F2.5-N7.5,839.0,Type I/II low-alkali portland cement,52.5,104.0,26.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,59.33,100 x 100 x 100,BS1881,122.5
3,S10-N10,839.0,Type I/II low-alkali portland cement,52.5,104.0,0.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,62.15,100 x 100 x 100,BS1881,116.0
4,S10-F5-M5,839.0,Type I/II low-alkali portland cement,52.5,104.0,52.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,64.98,100 x 100 x 100,BS1881,134.0

In [63]:
import pandas as pd
df = pd.read_csv("../data/UHPC_Cleaned.csv")

In [64]:
# Remove identifier column
df = df.drop(columns=["Mix_ID"])

In [65]:
df.head()

,Cement Amount (kg/m³),Cement type,Cement Grade (Mpa),Silica Fume (kg/m³),Flayash Amount (kg/m³),Limestone Powder (kg/m3),Quartzpowder (kg/m3),Glass powder (kg/m3),Rice husk ash (kg/m3),Metakaolin (kg/m³),...,Type of Fiber,Amount / Quantity of Fiber,Length (mm),Diameter (mm),Amount (kg/m³).1,Type of Superplasticizer,Amount (kg/m³).2,Specimen,Testing Standard,28-Day
0,839.0,Type I/II low-alkali portland cement,52.5,104.0,104.0,0.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,56.50,100 x 100 x 100,BS1881,135.0
1,839.0,Type I/II low-alkali portland cement,52.5,104.0,52.0,0.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,59.33,100 x 100 x 100,BS1881,132.0
2,839.0,Type I/II low-alkali portland cement,52.5,104.0,26.0,0.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,59.33,100 x 100 x 100,BS1881,122.5
3,839.0,Type I/II low-alkali portland cement,52.5,104.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,62.15,100 x 100 x 100,BS1881,116.0
4,839.0,Type I/II low-alkali portland cement,52.5,104.0,52.0,0.0,0.0,0.0,0.0,52.0,...,Straight Steel Fiber,119.0,13.0,0.2,147.0,Polycarboxylate-based HRWRA,64.98,100 x 100 x 100,BS1881,134.0

In [66]:
df.shape

(2188, 30)

In [67]:
df.columns.tolist()

['Cement Amount  (kg/m³)',
 'Cement type',
 'Cement Grade (Mpa)',
 'Silica Fume (kg/m³)',
 'Flayash Amount   (kg/m³)',
 'Limestone Powder  (kg/m3)',
 'Quartzpowder (kg/m3)',
 'Glass powder (kg/m3)',
 'Rice husk ash (kg/m3)',
 'Metakaolin (kg/m³)',
 'GGBFS  (kg/m³)',
 'Slag Amount   (kg/m³)',
 'Nano-CaCO3 (kg/m3)',
 'Nano-Al2O3 (kg/m3)',
 'Nano-TiO2 (kg/m3)',
 'Nano Silica (kg/m3)',
 'Filler (kg/m³)',
 'Amount  (kg/m³)',
 'Sand Type',
 'Max Size (mm)',
 'Type of Fiber',
 'Amount / Quantity of Fiber',
 'Length (mm)',
 'Diameter (mm)',
 'Amount  (kg/m³).1',
 'Type of Superplasticizer',
 'Amount  (kg/m³).2',
 'Specimen',
 'Testing Standard',
 '28-Day']

In [68]:
df.columns[-5:]

Index(['Type of Superplasticizer', 'Amount  (kg/m³).2', 'Specimen',
       'Testing Standard', '28-Day'],
      dtype='str')

In [69]:
df.dtypes

Cement Amount  (kg/m³)        float64
Cement type                       str
Cement Grade (Mpa)            float64
Silica Fume (kg/m³)           float64
Flayash Amount   (kg/m³)      float64
Limestone Powder  (kg/m3)     float64
Quartzpowder (kg/m3)          float64
Glass powder (kg/m3)          float64
Rice husk ash (kg/m3)         float64
Metakaolin (kg/m³)            float64
GGBFS  (kg/m³)                float64
Slag Amount   (kg/m³)         float64
Nano-CaCO3 (kg/m3)            float64
Nano-Al2O3 (kg/m3)            float64
Nano-TiO2 (kg/m3)             float64
Nano Silica (kg/m3)           float64
Filler (kg/m³)                float64
Amount  (kg/m³)               float64
Sand Type                         str
Max Size (mm)                     str
Type of Fiber                     str
Amount / Quantity of Fiber    float64
Length (mm)                   float64
Diameter (mm)                 float64
Amount  (kg/m³).1             float64
Type of Superplasticizer          str
Amount  (kg/m³).2             float64
Specimen                          str
Testing Standard                  str
28-Day                        float64
dtype: object

In [70]:
categorical_cols = df.select_dtypes(include=['object']).columns
print("Categorical Columns:")
print(categorical_cols)

Categorical Columns:
Index(['Cement type', 'Sand Type', 'Max Size (mm)', 'Type of Fiber',
       'Type of Superplasticizer', 'Specimen', 'Testing Standard'],
      dtype='str')

C:\Users\manvi\AppData\Local\Temp\ipykernel_13932\2737076198.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object']).columns

In [71]:
df_encoded = pd.get_dummies(df,columns=categorical_cols,drop_first=True)
print("Original Shape:",df.shape)
print("Encoded Shape:",df_encoded.shape)

Original Shape: (2188, 30)
Encoded Shape: (2188, 548)

In [72]:
df_encoded.head()

,Cement Amount (kg/m³),Cement Grade (Mpa),Silica Fume (kg/m³),Flayash Amount (kg/m³),Limestone Powder (kg/m3),Quartzpowder (kg/m3),Glass powder (kg/m3),Rice husk ash (kg/m3),Metakaolin (kg/m³),GGBFS (kg/m³),...,"Testing Standard_GB/T50081-2002, 2002; ASTM C39/C39M-18, 2018a",Testing Standard_GB177-85,Testing Standard_IS 4031-1988,Testing Standard_NF EN 196–1.,Testing Standard_NF EN196-1,Testing Standard_Swiss standard SIA 2052–2016,Testing Standard_TS EN 12390-3,Testing Standard_standard EN 12390,Testing Standard_standard-EN 196–1,Testing Standard_standard-EN 196–1
0,839.0,52.5,104.0,104.0,0.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
1,839.0,52.5,104.0,52.0,0.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
2,839.0,52.5,104.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
3,839.0,52.5,104.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
4,839.0,52.5,104.0,52.0,0.0,0.0,0.0,0.0,52.0,0.0,...,False,False,False,False,False,False,False,False,False,False

In [73]:
df_encoded.columns[-10:]

Index(['Testing Standard_GB/T50081-2002, 2002; ASTM C39/C39M-18, 2018a',
       'Testing Standard_GB177-85', 'Testing Standard_IS 4031-1988',
       'Testing Standard_NF EN 196–1.', 'Testing Standard_NF EN196-1',
       'Testing Standard_Swiss standard SIA 2052–2016',
       'Testing Standard_TS EN 12390-3', 'Testing Standard_standard EN 12390',
       'Testing Standard_standard-EN 196–1',
       'Testing Standard_standard-EN 196–1 '],
      dtype='str')

In [74]:
x = df_encoded.drop("28-Day",axis=1)
y = df_encoded["28-Day"]
print("Features:",x.shape)
print("Target:",y.shape)

Features: (2188, 547)
Target: (2188,)

In [75]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Features :", x_train.shape)
print("Testing Features  :", x_test.shape)
print("Training Target   :", y_train.shape)
print("Testing Target    :", y_test.shape)

Training Features : (1750, 547)
Testing Features  : (438, 547)
Training Target   : (1750,)
Testing Target    : (438,)

In [76]:
x = df_encoded.drop("28-Day", axis=1)   # Replace "28-Day" with your exact target column name
y = df_encoded["28-Day"]

print(x.shape)
print(y.shape)

(2188, 547)
(2188,)

In [77]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

print("x_train:", x_train.shape)
print("x_test :", x_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

x_train: (1750, 547)
x_test : (438, 547)
y_train: (1750,)
y_test : (438,)

In [78]:
x_train.to_csv("../data/x_train.csv", index=False)
x_test.to_csv("../data/x_test.csv", index=False)

y_train.to_csv("../data/y_train.csv", index=False)
y_test.to_csv("../data/y_test.csv", index=False)

print("Training and testing data saved successfully!")

Training and testing data saved successfully!

In [79]:
df_encoded.to_csv("../data/UHPC_Feature_Engineered.csv", index=False)

print("Feature Engineering Completed Successfully!")

Feature Engineering Completed Successfully!